### PR TITLE
Add timeout for HTTP requests

### LINKED ISSUE #3: Timeouts
This library does not support specifying timeouts for HTTP requests. This causes [issues](https://github.com/jenkinsci/fortify-plugin/issues/11) with longer operations like and FPR upload operation. `okhttp` read timeout is 10s, that is far too small for large FPRs and network bandwidth variances.

Original issue: jenkinsci/fortify-plugin#11

### PR DESCRIPTION
**Pull request by thezim**
Fixes #3.

### CODE REVIEW

**Comment by akaryakina** [comment]
Greg, this is a generated source code, we should not modify it. Can you think of a way to add your code so that it would survive the re-generation of the client?

**Comment by thezim** [comment]
I do not. I am unfamiliar with any of the frameworks used in this library nor am I a Java developer, sorry.

**Comment by thezim** [comment]
While partially agree you should not modify generated code this is swaggers purpose. To do most of the work for you. Surely why would it stub out:

https://github.com/fortify/ssc-restapi-client/blob/303eb16553cd9e46413e2f029b9176ab0053945a/src/main/java/com/fortify/ssc/restclient/ApiClient.java#L436 

And not intend you you to take advantage of it?

**Comment by akaryakina** [comment]
That's a good point. It looks like this this method needs to be called by Jenkins, right?

**Comment by thezim** [comment]
> That's a good point. It looks like this this method needs to be called by Jenkins, right?

No, my change works by on checking for the the existence of an environment variable for the time out values. If I doesn't find them then you get the default timeouts. This make the change non-breaking for any current consumers including jenkinsci/fortify-plugin. It is very easy to define environment variables in Jenkins before the Fortify plugin executes.

**Comment by akaryakina** [comment]
Timeouts have been added to the Fortify Jenkins plugin in 20.1 release of the plugin, no need to modify the generated source anymore.

**Pull request closed without merging**
